### ISSUE TITLE
Automatically delete files in board drone directory

### ISSUE THREAD

**Issue by loganfoote** [TheJabur/CCATpHive#15]
The vna and comb directories on the board fill up the board memory when large numbers of vna scans are taken. Older files should automatically be deleted so the board doesn't crash.

**Comment by TheJabur** [comment]
There is a python script called scripts/clean_board.py that will clean the board files as per some options. This is not done automatically yet because we did not want to delete data automatically that hasn't been uploaded off the board. You could setup a cron job to do it automatically if it's an issue for you. This is actually probably a good issue to bring up in the DAQ meeting so we can discuss desired behaviour.
